name: TGRNet
channels:
  - defaults
dependencies:
  - python==3.7.0
  - pip==20.2.4
  - pip:
    - dominate==2.5.1
    - imageio==2.8.0
    - networkx==2.3
    - numpy==1.18.2
    - opencv-python==4.4.0.46
    - pandas==1.0.3
    - pillow==7.1.1
    - torchfile==0.1.0
    - tqdm==4.45.0
    - visdom==0.1.8.9
    - polygon3==3.0.8
#   - pytorch==1.5.0
#   - torchvision==0.6.0
#   - torch-scatter==2.0.4
#   - torch-sparse==0.6.3
#   - torch-cluster==1.5.4
#   - torch-spline-conv==1.2.0
#   - torch-geometric==1.4.3